# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Mathematics of Quantum Information'
description:      'Workshops'
url:              https://MoQIT.github.io
baseurl:          ''

exclude: [ "LICENSE.hyde.md", "README.hyde.md" ]
